"""setup initial tables

Revision ID: eb5704c4f5a4
Revises: 
Create Date: 2026-04-30 02:01:40.052319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb5704c4f5a4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('no_telp', sa.String(length=20), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('email')
    )
    op.create_table('mahasiswa',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('nim', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('nim')
    )
    op.create_table('penjaga_ruangan',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('nip', sa.String(length=30), nullable=False),
    sa.Column('unit_kerja', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('nip')
    )
    op.create_table('pic_ruangan',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('nip', sa.String(length=30), nullable=False),
    sa.Column('unit_kerja', sa.String(length=100), nullable=False),
    sa.Column('jabatan', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('nip')
    )
    op.create_table('ruangan',
    sa.Column('id_ruangan', sa.Integer(), nullable=False),
    sa.Column('nama_ruangan', sa.String(length=100), nullable=False),
    sa.Column('kapasitas', sa.Integer(), nullable=False),
    sa.Column('fasilitas', sa.Text(), nullable=False),
    sa.Column('biaya_peminjaman', sa.Integer(), nullable=False),
    sa.Column('id_pic', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_pic'], ['pic_ruangan.id_user'], ),
    sa.PrimaryKeyConstraint('id_ruangan')
    )
    op.create_table('peminjaman',
    sa.Column('id_booking', sa.Integer(), nullable=False),
    sa.Column('waktu_mulai', sa.DateTime(), nullable=False),
    sa.Column('waktu_selesai', sa.DateTime(), nullable=False),
    sa.Column('keperluan', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('path_file_bukti', sa.String(length=255), nullable=True),
    sa.Column('id_epass', sa.String(length=50), nullable=True),
    sa.Column('id_mahasiswa', sa.Integer(), nullable=False),
    sa.Column('id_ruangan', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_mahasiswa'], ['mahasiswa.id_user'], ),
    sa.ForeignKeyConstraint(['id_ruangan'], ['ruangan.id_ruangan'], ),
    sa.PrimaryKeyConstraint('id_booking')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('peminjaman')
    op.drop_table('ruangan')
    op.drop_table('pic_ruangan')
    op.drop_table('penjaga_ruangan')
    op.drop_table('mahasiswa')
    op.drop_table('user')
    # ### end Alembic commands ###
